Decrease indentation level

diff --git a/rpswin/bin/bks b/rpswin/bin/bks
--- a/rpswin/bin/bks
+++ b/rpswin/bin/bks
@@ -2,73 +2,73 @@
 
 declare -a hosts
 for arg in "$@"; do
-    case $arg in
-	--sync)
-	    sync=1
-	    ;;
-	--run=*)
-	    runcmd=${arg##--run=}
-	    ;;
-	-*)
-	    echo "invalid argument $arg" >&2
-	    exit 1
-	    ;;
-	*)
-	    hosts+=("$arg")
-	    ;;
-    esac
+  case $arg in
+    --sync)
+      sync=1
+      ;;
+    --run=*)
+      runcmd=${arg##--run=}
+      ;;
+    -*)
+      echo "invalid argument $arg" >&2
+      exit 1
+      ;;
+    *)
+      hosts+=("$arg")
+      ;;
+  esac
 done
 echo "${hosts[@]}"
 
 syncdbfile=~/db/hostsync
 if [[ -r $syncdbfile ]]; then
-    . $syncdbfile
+  . $syncdbfile
 else
-    declare -A syncdb
+  declare -A syncdb
 fi
 
 for h in "${hosts[@]}"; do
-    host="$h"
-    for dom in .dc.polisen.se .pki.polisen.se .mgmt.polisen.se .bd.polisen.se .polisen.se ''; do
-        # Use ping to find domain
-        fqdn=$(ping -n 1 "${h}$dom" 2>/dev/null | awk '/^Pinging/{print $2}')
-        if [[ $fqdn ]]; then
-            domain=${fqdn#*.}
-            host=${host%%.*}
-            break
-	fi
-    done
+  host="$h"
+  for dom in .dc.polisen.se .pki.polisen.se .mgmt.polisen.se .bd.polisen.se .polisen.se ''; do
+    # Use ping to find domain
+    fqdn=$(ping -n 1 "${h}$dom" 2>/dev/null | awk '/^Pinging/{print $2}')
+    if [[ $fqdn ]]; then
+      domain=${fqdn#*.}
+      host=${host%%.*}
+      break
+    fi
+  done
 
-    if [[ $domain == 'pki.polisen.se' || $host == 'boksm' ]]; then
-      session=Boks
-      user=a0043002
-    else
-      session=Linux
-      user=u0043002
-    fi
+  if [[ $domain == 'pki.polisen.se' || $host == 'boksm' ]]; then
+    session=Boks
+    user=a0043002
+  else
+    session=Linux
+    user=u0043002
+  fi
 
-    if [[ $runcmd ]]; then
-	echo "*** ${fqdn}"
-	blink -load "$session" "${user}@${fqdn}" "$runcmd"
-	continue;
-    fi
-    if [[ ! ${syncdb["${fqdn}"]} ]]; then
-	sync=1
-    fi
-    if [[ $sync ]]; then
-	set -x
-	blink -load "$session" "${user}@${fqdn}" date
-	tar --create --file=- --directory="${HOME}" --no-recursion \
-	  --files-from="${HOME}/db/dotfiles" \
-	  | blink -load "$session" "${user}@${fqdn}" tar xf -
-	set +x
-	syncdb["${fqdn}"]=$(date +%s)
-	synced=1
-    fi
+  if [[ $runcmd ]]; then
+    echo "*** ${fqdn}"
+    blink -load "$session" "${user}@${fqdn}" "$runcmd"
+    continue;
+  fi
+  if [[ ! ${syncdb["${fqdn}"]} ]]; then
+    sync=1
+  fi
+  if [[ $sync ]]; then
+    set -x
+    blink -load "$session" "${user}@${fqdn}" date
+    tar --create --file=- --directory="${HOME}" --no-recursion \
+      --files-from="${HOME}/db/dotfiles" \
+      | blink -load "$session" "${user}@${fqdn}" tar xf -
+    set +x
+    syncdb["${fqdn}"]=$(date +%s)
+    synced=1
+  fi
 
-    if [[ ${synced} ]]; then
-	declare -p syncdb > $syncdbfile
-    fi
-    echo bokssh -load "$session" "${user}@${fqdn}"
-    nohup bokssh -load "$session" "${user}@${fqdn}" > /dev/null 2>&1 &
+  if [[ ${synced} ]]; then
+    declare -p syncdb > $syncdbfile
+  fi
+  echo bokssh -load "$session" "${user}@${fqdn}"
+  nohup bokssh -load "$session" "${user}@${fqdn}" > /dev/null 2>&1 &
 done
