Add option --sync

diff --git a/rpswin/bin/bks b/rpswin/bin/bks
--- a/rpswin/bin/bks
+++ b/rpswin/bin/bks
@@ -1,5 +1,17 @@
 #! /bin/bash
 
+while [[ "$#" -gt 0 ]]; do
+    case $1 in
+        --sync) sync=1;;
+        *)
+            echo "invalid option $1"
+            exit 1
+            ;;
+    esac
+    shift
+done
+
+
 
 for h in "$@"; do
     for dom in '' .dc.polisen.se .pki.polisen.se .polisen.se; do
@@ -10,6 +22,10 @@ for h in "$@"; do
     done
 
     user=u0043002
+
+    if [[ $sync ]]; then
+	tar --create --file=- --directory="${HOME}" --no-recursion --files-from="${HOME}/db/dotfiles" | blink "${user}@${host}" tar xf -
+    fi
 
     echo bokssh "${user}@${host}"
     nohup bokssh "${user}@${host}" > /dev/null 2>&1 &
